/*NAME: SN_PROD table
STORY_ID:20190725(2)
DESCRIPTION: TRIGERS FOR THE TABLE SN_PROD
1.TR_SN_PROD_BI: FOR AUTO GENERATION OF SYS_CRD_DATE FIELD
2.TR_SN_PROD_BU:FOR AUTO GENERATION OF SYS_LST_MOD_DATE FIELD
3.TR_SN_PROD_BD:FOR AUTO GENERATION OF SYS_LST_MOD_DATE FIELD
4.PROD_ID_PARENT:FOR AUTO GENERATION OF PARENT PRODUCTS ID
5.PROD_ID_CHILD:FOR AUTO GENERATION OF CHILD PRODUCTS ID

DATE:25/07/2019
APPROVED BY:
*/

/* TRIGGER FOR SYS_CRE_DATE*/
CREATE OR REPLACE TRIGGER TR_SN_PROD_BI
         BEFORE  insert 
         ON SN_PROD
         FOR EACH ROW
         DECLARE
    begin
            :new.SYS_CRD_DATE:= sysdate;
            
    end;
    
/* TRIGGERS FOR SYS_LST_MOD_DATE BEFORE INSERT OR UPDATE*/
    CREATE OR REPLACE TRIGGER TR_SN_PROD_BU
         BEFORE  INSERT OR UPDATE 
         ON SN_PROD
         FOR EACH ROW
         DECLARE
    begin
            :new.SYS_LST_MOD_DATE:= sysdate;
    end;

/* TRIGGERS FOR SYS_LST_MOD_DATE BEFORE INSERT OR DELETE*/
    
     CREATE OR REPLACE TRIGGER TR_SN_PROD_BD
         BEFORE  INSERT OR DELETE
         ON SN_PROD
         FOR EACH ROW
         DECLARE
    begin
            :new.SYS_LST_MOD_DATE:= sysdate;
    end;
    
/*TRIGGER FOR INSERTING PARENT PRODUCT ID'S INTO  TABLE*/

CREATE OR REPLACE TRIGGER PROD_ID_PARENT
AFTER INSERT ON SN_PROD
FOR EACH ROW
  WHEN (new.IS_PARNT_PROD = 1)
BEGIN
  :new.PROD_ID :=PROD_ID_PARENT.NEXTVAL;
  :new.PARNT_PROD_ID :=PROD_ID_PARENT.NEXTVAL;
END;

/*TRIGGER FOR INSERTING CHILD PRODUCT ID'S INTO TABLE*/

CREATE OR REPLACE TRIGGER PROD_ID_CHILD
AFTER INSERT ON SN_PROD
FOR EACH ROW
  WHEN (new.IS_PARNT_PROD = 0)
BEGIN
  :new.PROD_ID :=PROD_ID_CHILD.NEXTVAL;
  :new.PARNT_PROD_ID :=PROD_ID_PARENT.CURRVAL;
END;
