 /*NAME: EMPLOYEE_DETAILS table
STORY_ID:20190713(1)
DESCRIPTION: A table "EMPLOYE_DETAILS" is created to maintain information regarding all the EMPLOYEE DETAILS(INDIVIDUALLY) of organization 
DATE:13/07/2019
APPROVED BY:
*/

/*CREATING EMPLOYEE_DETAILS TABLE*/

 CREATE TABLE "SIMS"."EMPLOYEE_DETAILS" 
   ("EMP_ID" VARCHAR2(20 BYTE), 
	"EMP_NAME" VARCHAR2(30 BYTE), 
	"EMAIL_ID" VARCHAR2(30 BYTE), 
	"DEPT_ID" VARCHAR2(20 BYTE), 
	"DOJ" DATE, 
	"PAN_NUMBER" VARCHAR2(20 BYTE), 
	"AADHAR_NUMBER" VARCHAR2(20 BYTE), 
	"WORK_EXP" NUMBER, 
	"PREV_ORG" VARCHAR2(20 BYTE), 
	"RELEV_DATE" DATE, 
	"REPORTING_ID" VARCHAR2(20 BYTE), 
	"MANAGER_ID" VARCHAR2(20 BYTE), 
	"HIGH_QUAL" VARCHAR2(20 BYTE), 
	"SYS_CRE_DATE" DATE, 
	"SYS_LST_MOD_DATE" DATE, 
	"QR" BLOB, 
	"IMG" BLOB, 
	"BLOOD_GROUP" VARCHAR2(20 BYTE), 
	"TSHIRT_SIZE" VARCHAR2(20 BYTE), 
	"EMERG_ADDRESS" VARCHAR2(100 BYTE), 
	"PERMA_ADDRESS" VARCHAR2(100 BYTE), 
	"PLACE_OF_REP" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"CITY_CODE" NUMBER
   );