/*NAME: EMPLOYEE_DETAILS table
STORY_ID:20190713(2)
DESCRIPTION: A table "EMPLOYE_DETAILS" is created to maintain information regarding all the EMPLOYEE DETAILS(INDIVIDUALLY) of organization and TRIGGERS ["EMP","EMPLOYEE"] are created to generate SYS Date and EMP_ID automatically using SEQUENCE "EMP_SEQ".
DATE:13/07/2019
APPROVED BY:
*/

/*DISABLING  TRIGGERS ON TABLE EMPLOYEE_DETAILS*/

ALTER TABLE EMPLOYEE_DETAILS DISABLE ALL TRIGGERS;

/*CREATING EMPLOYEE_DETAILS TABLE*/

CREATE TABLE EMPLOYEE_DETAILS
(
EMP_ID VARCHAR(10) NOT NULL,
EMP_NAME VARCHAR(30),
EMAIL_ID VARCHAR(30),
DEPT_ID VARCHAR(10),
DOJ DATE,
PAN_NUMBER VARCHAR(20),
AADHAR_NUMBER VARCHAR(20),
WORK_EXP NUMBER,
PREV_ORG VARCHAR(20),
RELEV_DATE DATE,
REPORTING_ID VARCHAR(10),
MANAGER_ID VARCHAR(10),
HIGH_QUAL VARCHAR(20),
SYS_CRE_DATE DATE,
SYS_LST_MOD_DATE DATE,
CONSTRAINT EMPLOYEE_DETAILS_pk PRIMARY KEY (EMP_ID)  
); 

/* TRIGGER FOR SYS DATE*/

CREATE OR REPLACE TRIGGER EMPLOYEE
         BEFORE update or insert or delete
         ON EMPLOYEE_DETAILS
         FOR EACH ROW
         DECLARE
    begin
            :new.SYS_CRE_DATE:= sysdate;
            :new.SYS_LST_MOD_DATE:= sysdate;
    end;

    /* TRIGGER FOR EMP_ID GENERATION USING SEQUENCE*/

    CREATE OR REPLACE TRIGGER EMP
  BEFORE INSERT ON EMPLOYEE_DETAILS
  FOR EACH ROW
BEGIN
  SELECT EMP_SEQ.nextval
  INTO :new.EMP_ID
  FROM dual;
END;

/*SEQUENCE FOR EMP_ID GENERATION*/

  CREATE SEQUENCE EMP_SEQ
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 truncate table EMPLOYEE_DETAILS;

/* INSERTING DATA INTO ROLES TABLE*/

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Abhilash Dasari','abhilash@smartnerd.co.in',TO_DATE('01/04/2018', 'DD/MM/YYYY'),'ASNPD7263R','856296965325');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Pradeep Reddy Sama','pradeep@smartnerd.co.in',TO_DATE('01/04/2018', 'DD/MM/YYYY')	,'BDUPS4162H','509792813042');	

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,AADHAR_NUMBER) 
VALUES('Vinod Kethavath','vinod@smartnerd.co.in',TO_DATE('20/07/2018', 'DD/MM/YYYY'),'696130274813');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('M S S Naga Pratap',	'pratap@smartnerd.co.in',TO_DATE('01/11/2018', 'DD/MM/YYYY'),'SPM4413P','288004832214');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Sandeep Vamigari','sandeep@smartnerd.co.in',TO_DATE('01/11/2018', 'DD/MM/YYYY'),'AIDPV1603K','343777676920');	

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Srinivas Vijaya Krishna V','srinivas@smartnerd.co.in',TO_DATE('10/12/2018', 'DD/MM/YYYY'),'BVDPS4086D','920767898650');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Sai Roopesh K','sairoopesh@smartnerd.co.in',TO_DATE('02/01/2019', 'DD/MM/YYYY'),'BTAPS3790P','349280768687');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Uday Kannuri','uday@smartnerd.co.in',TO_DATE('01/03/2019', 'DD/MM/YYYY'),'HJCPK6070E','806149433118');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Harish Goud Musirigari','harish@smartnerd.co.in',TO_DATE('04/04/2019', 'DD/MM/YYYY'),'APEPM6831L','556744389245	');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Syed Asif Ali','ali@smartnerd.co.in',TO_DATE('17/04/2019', 'DD/MM/YYYY'),'BQZPA9414Q','457386615602');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Srujana Vulupala','srujana@smartnerd.co.in	Admin',TO_DATE('01/05/2019', 'DD/MM/YYYY'),'BNUPB9515P','206336670705');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Santosh Kumar Idha','santosh@smartnerd.co.in	',TO_DATE('01/05/2019', 'DD/MM/YYYY'),'ACYI1415R','705176900081');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,AADHAR_NUMBER) 
VALUES('Srujan Goud M'	,'srujan@smartnerd.co.in',TO_DATE('01/05/2019', 'DD/MM/YYYY'),'892377243527');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('Karthik Yadav Kurumathi'	,'karthik@smartnerd.co.in	',TO_DATE('04/05/2019', 'DD/MM/YYYY'),'CHDPK9227M	','892377243527');

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ) 
VALUES('Sairam Kaparthi','sairam@smartnerd.co.in',TO_DATE('01/06/2019', 'DD/MM/YYYY'));

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ,PAN_NUMBER,AADHAR_NUMBER) 
VALUES('S Sarath Chandra Makineni','sarath@smartnerd.co.in',TO_DATE('04/06/2019', 'DD/MM/YYYY'),'AWQPM4683H','989289477546');	

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ)
VALUES('Deeksha Sharma','deeksha@smartnerd.co.in',TO_DATE('11/06/2019', 'DD/MM/YYYY'));

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ) 
VALUES('Sai Eshwar Gajawada','eshwar@smartnerd.co.in',TO_DATE('11/06/2019', 'DD/MM/YYYY'));

INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ) 
VALUES('Sai Krishna K','saikrishna@smartnerd.co.in',TO_DATE('11/06/2019', 'DD/MM/YYYY'));	


INSERT INTO EMPLOYEE_DETAILS(EMP_NAME,EMAIL_ID,DOJ) 
VALUES('Nikhil Raj B','nikhil@smartnerd.co.in',	TO_DATE('11/06/2019', 'DD/MM/YYYY'));			
								

/* DISPLAYS DATA IN TABLE*/

SELECT * FROM EMPLOYEE_DETAILS;


/*ENABLING  TRIGGERS ON TABLE EMPLOYEE_DETAILS*/

ALTER TABLE EMPLOYEE_DETAILS ENABLE ALL TRIGGERS;